apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wp-app
    type: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
      type: db
  template:
    metadata:
      name: mysql-pod
      labels:
        app: wp-app
        type: db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - db
      containers:
      - name: mysql-container
        image: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: mysql-password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-host-config
              key: database-name


# mariadb port değişecek
# wp pod içinde serverName değişecek.

