apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wp-app
    type: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
      type: client
  template:
    metadata:
      name: wp-pod
      labels:
        app: wp-app
        type: client
    spec:
      containers:
      - name: wp-container
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-host-config
              key: database-url
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-host-config
              key: database-name
        - name: WORDPRESS_TABLE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: mysql-host-config
              key: table-prefix
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-secret
              key: mysql-password

        volumeMounts:
        - mountPath: /etc/apache2/sites-available/k8s.conf
          subPath: k8s.conf
          name: wp-config-volume
      volumes:
      - name: wp-config-volume
        configMap:
          name: wp-config
          items:
          - key: k8s.conf
            path: k8s.conf

